// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: product/messages.proto

package product

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProductStatus int32

const (
	ProductStatus_PRODUCT_STATUS_UNSPECIFIED ProductStatus = 0 // Unspecified status (default)
	ProductStatus_ACTIVE                     ProductStatus = 1 // Product is active and available
	ProductStatus_INACTIVE                   ProductStatus = 2 // Product is inactive and unavailable
)

// Enum value maps for ProductStatus.
var (
	ProductStatus_name = map[int32]string{
		0: "PRODUCT_STATUS_UNSPECIFIED",
		1: "ACTIVE",
		2: "INACTIVE",
	}
	ProductStatus_value = map[string]int32{
		"PRODUCT_STATUS_UNSPECIFIED": 0,
		"ACTIVE":                     1,
		"INACTIVE":                   2,
	}
)

func (x ProductStatus) Enum() *ProductStatus {
	p := new(ProductStatus)
	*p = x
	return p
}

func (x ProductStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProductStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_product_messages_proto_enumTypes[0].Descriptor()
}

func (ProductStatus) Type() protoreflect.EnumType {
	return &file_product_messages_proto_enumTypes[0]
}

func (x ProductStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProductStatus.Descriptor instead.
func (ProductStatus) EnumDescriptor() ([]byte, []int) {
	return file_product_messages_proto_rawDescGZIP(), []int{0}
}

// ===== Utility Messages =====
type ErrorCode int32

const (
	ErrorCode_ERROR_CODE_UNSPECIFIED ErrorCode = 0 // Unspecified error code
	ErrorCode_NOT_FOUND              ErrorCode = 1 // Resource not found
	ErrorCode_INVALID_ARGUMENT       ErrorCode = 2 // Invalid argument provided
	ErrorCode_INTERNAL               ErrorCode = 3 // Internal server error
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0: "ERROR_CODE_UNSPECIFIED",
		1: "NOT_FOUND",
		2: "INVALID_ARGUMENT",
		3: "INTERNAL",
	}
	ErrorCode_value = map[string]int32{
		"ERROR_CODE_UNSPECIFIED": 0,
		"NOT_FOUND":              1,
		"INVALID_ARGUMENT":       2,
		"INTERNAL":               3,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_product_messages_proto_enumTypes[1].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_product_messages_proto_enumTypes[1]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_product_messages_proto_rawDescGZIP(), []int{1}
}

// ===== Product Messages =====
type CreateProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShopId        string                 `protobuf:"bytes,1,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`                                                                     // ID of the shop to which the product belongs
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                                                                       // Product name
	Slug          string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`                                                                                       // Product slug (URL-friendly identifier)
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`                                                                         // Product description
	Price         float64                `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`                                                                                   // Product price
	CategoryId    string                 `protobuf:"bytes,6,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`                                                         // Product category
	Sku           string                 `protobuf:"bytes,7,opt,name=sku,proto3" json:"sku,omitempty"`                                                                                         // Product SKU
	Stock         int32                  `protobuf:"varint,8,opt,name=stock,proto3" json:"stock,omitempty"`                                                                                    // Available stock quantity
	Attributes    map[string]string      `protobuf:"bytes,9,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Additional product attributes
	Images        []string               `protobuf:"bytes,10,rep,name=images,proto3" json:"images,omitempty"`                                                                                  // URLs of product images
	Status        ProductStatus          `protobuf:"varint,11,opt,name=status,proto3,enum=product.ProductStatus" json:"status,omitempty"`                                                      // Product status (e.g., active, inactive)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductRequest) Reset() {
	*x = CreateProductRequest{}
	mi := &file_product_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductRequest) ProtoMessage() {}

func (x *CreateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductRequest.ProtoReflect.Descriptor instead.
func (*CreateProductRequest) Descriptor() ([]byte, []int) {
	return file_product_messages_proto_rawDescGZIP(), []int{0}
}

func (x *CreateProductRequest) GetShopId() string {
	if x != nil {
		return x.ShopId
	}
	return ""
}

func (x *CreateProductRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProductRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *CreateProductRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateProductRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateProductRequest) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *CreateProductRequest) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *CreateProductRequest) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *CreateProductRequest) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *CreateProductRequest) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *CreateProductRequest) GetStatus() ProductStatus {
	if x != nil {
		return x.Status
	}
	return ProductStatus_PRODUCT_STATUS_UNSPECIFIED
}

type CreateProductResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*CreateProductResponse_ProductId
	//	*CreateProductResponse_Error
	Result        isCreateProductResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductResponse) Reset() {
	*x = CreateProductResponse{}
	mi := &file_product_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductResponse) ProtoMessage() {}

func (x *CreateProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductResponse.ProtoReflect.Descriptor instead.
func (*CreateProductResponse) Descriptor() ([]byte, []int) {
	return file_product_messages_proto_rawDescGZIP(), []int{1}
}

func (x *CreateProductResponse) GetResult() isCreateProductResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *CreateProductResponse) GetProductId() string {
	if x != nil {
		if x, ok := x.Result.(*CreateProductResponse_ProductId); ok {
			return x.ProductId
		}
	}
	return ""
}

func (x *CreateProductResponse) GetError() *ErrorResponse {
	if x != nil {
		if x, ok := x.Result.(*CreateProductResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isCreateProductResponse_Result interface {
	isCreateProductResponse_Result()
}

type CreateProductResponse_ProductId struct {
	ProductId string `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3,oneof"` // ID of the newly created product
}

type CreateProductResponse_Error struct {
	Error *ErrorResponse `protobuf:"bytes,2,opt,name=error,proto3,oneof"` // Error response if creation failed
}

func (*CreateProductResponse_ProductId) isCreateProductResponse_Result() {}

func (*CreateProductResponse_Error) isCreateProductResponse_Result() {}

type CreateCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`               // Category name
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"` // Category description
	Attributes    []*CategoryAttribute   `protobuf:"bytes,3,rep,name=attributes,proto3" json:"attributes,omitempty"`   // List of category attributes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCategoryRequest) Reset() {
	*x = CreateCategoryRequest{}
	mi := &file_product_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCategoryRequest) ProtoMessage() {}

func (x *CreateCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCategoryRequest.ProtoReflect.Descriptor instead.
func (*CreateCategoryRequest) Descriptor() ([]byte, []int) {
	return file_product_messages_proto_rawDescGZIP(), []int{2}
}

func (x *CreateCategoryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCategoryRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateCategoryRequest) GetAttributes() []*CategoryAttribute {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type CreateCategoryResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*CreateCategoryResponse_CategoryId
	//	*CreateCategoryResponse_Error
	Result        isCreateCategoryResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCategoryResponse) Reset() {
	*x = CreateCategoryResponse{}
	mi := &file_product_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCategoryResponse) ProtoMessage() {}

func (x *CreateCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCategoryResponse.ProtoReflect.Descriptor instead.
func (*CreateCategoryResponse) Descriptor() ([]byte, []int) {
	return file_product_messages_proto_rawDescGZIP(), []int{3}
}

func (x *CreateCategoryResponse) GetResult() isCreateCategoryResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *CreateCategoryResponse) GetCategoryId() string {
	if x != nil {
		if x, ok := x.Result.(*CreateCategoryResponse_CategoryId); ok {
			return x.CategoryId
		}
	}
	return ""
}

func (x *CreateCategoryResponse) GetError() *ErrorResponse {
	if x != nil {
		if x, ok := x.Result.(*CreateCategoryResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isCreateCategoryResponse_Result interface {
	isCreateCategoryResponse_Result()
}

type CreateCategoryResponse_CategoryId struct {
	CategoryId string `protobuf:"bytes,1,opt,name=category_id,json=categoryId,proto3,oneof"` // ID of the newly created category
}

type CreateCategoryResponse_Error struct {
	Error *ErrorResponse `protobuf:"bytes,2,opt,name=error,proto3,oneof"` // Error response if creation failed
}

func (*CreateCategoryResponse_CategoryId) isCreateCategoryResponse_Result() {}

func (*CreateCategoryResponse_Error) isCreateCategoryResponse_Result() {}

type CategoryAttribute struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`                                                                                   // Attribute key
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`                                                                               // Attribute label
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`                                                                                 // Attribute type (e.g., string, number, boolean)
	Required      bool                   `protobuf:"varint,4,opt,name=required,proto3" json:"required,omitempty"`                                                                        // Whether the attribute is required
	Options       map[string]string      `protobuf:"bytes,5,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Options for the attribute (if applicable)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryAttribute) Reset() {
	*x = CategoryAttribute{}
	mi := &file_product_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryAttribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryAttribute) ProtoMessage() {}

func (x *CategoryAttribute) ProtoReflect() protoreflect.Message {
	mi := &file_product_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryAttribute.ProtoReflect.Descriptor instead.
func (*CategoryAttribute) Descriptor() ([]byte, []int) {
	return file_product_messages_proto_rawDescGZIP(), []int{4}
}

func (x *CategoryAttribute) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CategoryAttribute) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *CategoryAttribute) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CategoryAttribute) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *CategoryAttribute) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

type ErrorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=product.ErrorCode" json:"code,omitempty"` // Error code enum
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                   // Error message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	mi := &file_product_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_product_messages_proto_rawDescGZIP(), []int{5}
}

func (x *ErrorResponse) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_ERROR_CODE_UNSPECIFIED
}

func (x *ErrorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_product_messages_proto protoreflect.FileDescriptor

const file_product_messages_proto_rawDesc = "" +
	"\n" +
	"\x16product/messages.proto\x12\aproduct\"\xae\x03\n" +
	"\x14CreateProductRequest\x12\x17\n" +
	"\ashop_id\x18\x01 \x01(\tR\x06shopId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price\x12\x1f\n" +
	"\vcategory_id\x18\x06 \x01(\tR\n" +
	"categoryId\x12\x10\n" +
	"\x03sku\x18\a \x01(\tR\x03sku\x12\x14\n" +
	"\x05stock\x18\b \x01(\x05R\x05stock\x12M\n" +
	"\n" +
	"attributes\x18\t \x03(\v2-.product.CreateProductRequest.AttributesEntryR\n" +
	"attributes\x12\x16\n" +
	"\x06images\x18\n" +
	" \x03(\tR\x06images\x12.\n" +
	"\x06status\x18\v \x01(\x0e2\x16.product.ProductStatusR\x06status\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"r\n" +
	"\x15CreateProductResponse\x12\x1f\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tH\x00R\tproductId\x12.\n" +
	"\x05error\x18\x02 \x01(\v2\x16.product.ErrorResponseH\x00R\x05errorB\b\n" +
	"\x06result\"\x89\x01\n" +
	"\x15CreateCategoryRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12:\n" +
	"\n" +
	"attributes\x18\x03 \x03(\v2\x1a.product.CategoryAttributeR\n" +
	"attributes\"u\n" +
	"\x16CreateCategoryResponse\x12!\n" +
	"\vcategory_id\x18\x01 \x01(\tH\x00R\n" +
	"categoryId\x12.\n" +
	"\x05error\x18\x02 \x01(\v2\x16.product.ErrorResponseH\x00R\x05errorB\b\n" +
	"\x06result\"\xea\x01\n" +
	"\x11CategoryAttribute\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1a\n" +
	"\brequired\x18\x04 \x01(\bR\brequired\x12A\n" +
	"\aoptions\x18\x05 \x03(\v2'.product.CategoryAttribute.OptionsEntryR\aoptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"Q\n" +
	"\rErrorResponse\x12&\n" +
	"\x04code\x18\x01 \x01(\x0e2\x12.product.ErrorCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*I\n" +
	"\rProductStatus\x12\x1e\n" +
	"\x1aPRODUCT_STATUS_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06ACTIVE\x10\x01\x12\f\n" +
	"\bINACTIVE\x10\x02*Z\n" +
	"\tErrorCode\x12\x1a\n" +
	"\x16ERROR_CODE_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tNOT_FOUND\x10\x01\x12\x14\n" +
	"\x10INVALID_ARGUMENT\x10\x02\x12\f\n" +
	"\bINTERNAL\x10\x03B\x1eZ\x1cshared/proto/product;productb\x06proto3"

var (
	file_product_messages_proto_rawDescOnce sync.Once
	file_product_messages_proto_rawDescData []byte
)

func file_product_messages_proto_rawDescGZIP() []byte {
	file_product_messages_proto_rawDescOnce.Do(func() {
		file_product_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_product_messages_proto_rawDesc), len(file_product_messages_proto_rawDesc)))
	})
	return file_product_messages_proto_rawDescData
}

var file_product_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_product_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_product_messages_proto_goTypes = []any{
	(ProductStatus)(0),             // 0: product.ProductStatus
	(ErrorCode)(0),                 // 1: product.ErrorCode
	(*CreateProductRequest)(nil),   // 2: product.CreateProductRequest
	(*CreateProductResponse)(nil),  // 3: product.CreateProductResponse
	(*CreateCategoryRequest)(nil),  // 4: product.CreateCategoryRequest
	(*CreateCategoryResponse)(nil), // 5: product.CreateCategoryResponse
	(*CategoryAttribute)(nil),      // 6: product.CategoryAttribute
	(*ErrorResponse)(nil),          // 7: product.ErrorResponse
	nil,                            // 8: product.CreateProductRequest.AttributesEntry
	nil,                            // 9: product.CategoryAttribute.OptionsEntry
}
var file_product_messages_proto_depIdxs = []int32{
	8, // 0: product.CreateProductRequest.attributes:type_name -> product.CreateProductRequest.AttributesEntry
	0, // 1: product.CreateProductRequest.status:type_name -> product.ProductStatus
	7, // 2: product.CreateProductResponse.error:type_name -> product.ErrorResponse
	6, // 3: product.CreateCategoryRequest.attributes:type_name -> product.CategoryAttribute
	7, // 4: product.CreateCategoryResponse.error:type_name -> product.ErrorResponse
	9, // 5: product.CategoryAttribute.options:type_name -> product.CategoryAttribute.OptionsEntry
	1, // 6: product.ErrorResponse.code:type_name -> product.ErrorCode
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_product_messages_proto_init() }
func file_product_messages_proto_init() {
	if File_product_messages_proto != nil {
		return
	}
	file_product_messages_proto_msgTypes[1].OneofWrappers = []any{
		(*CreateProductResponse_ProductId)(nil),
		(*CreateProductResponse_Error)(nil),
	}
	file_product_messages_proto_msgTypes[3].OneofWrappers = []any{
		(*CreateCategoryResponse_CategoryId)(nil),
		(*CreateCategoryResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_product_messages_proto_rawDesc), len(file_product_messages_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_product_messages_proto_goTypes,
		DependencyIndexes: file_product_messages_proto_depIdxs,
		EnumInfos:         file_product_messages_proto_enumTypes,
		MessageInfos:      file_product_messages_proto_msgTypes,
	}.Build()
	File_product_messages_proto = out.File
	file_product_messages_proto_goTypes = nil
	file_product_messages_proto_depIdxs = nil
}
