// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: auth/messages.proto

package auth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorCode int32

const (
	ErrorCode_ERROR_CODE_UNSPECIFIED ErrorCode = 0 // Unspecified error (default)
	ErrorCode_INVALID_CREDENTIALS    ErrorCode = 1 // Email or password is incorrect
	ErrorCode_USER_NOT_FOUND         ErrorCode = 2 // User does not exist
	ErrorCode_TOKEN_EXPIRED          ErrorCode = 3 // Token has expired
	ErrorCode_TOKEN_INVALID          ErrorCode = 4 // Token is invalid or corrupted
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0: "ERROR_CODE_UNSPECIFIED",
		1: "INVALID_CREDENTIALS",
		2: "USER_NOT_FOUND",
		3: "TOKEN_EXPIRED",
		4: "TOKEN_INVALID",
	}
	ErrorCode_value = map[string]int32{
		"ERROR_CODE_UNSPECIFIED": 0,
		"INVALID_CREDENTIALS":    1,
		"USER_NOT_FOUND":         2,
		"TOKEN_EXPIRED":          3,
		"TOKEN_INVALID":          4,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_auth_messages_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_auth_messages_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_auth_messages_proto_rawDescGZIP(), []int{0}
}

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`                                // User email address
	FirstName     string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`       // User's first name
	LastName      string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`          // User's last name
	PhoneNumber   string                 `protobuf:"bytes,4,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"` // User's phone number
	Password      string                 `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`                          // User's password (hashed on server)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_auth_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_auth_messages_proto_rawDescGZIP(), []int{0}
}

func (x *CreateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateUserRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *CreateUserRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *CreateUserRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *CreateUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type CreateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                             // User ID
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`                                       // User email
	EmailVerified bool                   `protobuf:"varint,3,opt,name=email_verified,json=emailVerified,proto3" json:"email_verified,omitempty"` // Whether email is verified
	FirstName     string                 `protobuf:"bytes,4,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`              // User's first name
	LastName      string                 `protobuf:"bytes,5,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`                 // User's last name
	PhoneNumber   string                 `protobuf:"bytes,6,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`        // User's phone number
	IsActive      bool                   `protobuf:"varint,7,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`                // Whether user is active
	RoleId        string                 `protobuf:"bytes,8,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`                       // User's role ID
	CreatedAt     int64                  `protobuf:"varint,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`             // Account creation timestamp
	UpdatedAt     int64                  `protobuf:"varint,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`            // Last update timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserResponse) Reset() {
	*x = CreateUserResponse{}
	mi := &file_auth_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResponse) ProtoMessage() {}

func (x *CreateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResponse.ProtoReflect.Descriptor instead.
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return file_auth_messages_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUserResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateUserResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateUserResponse) GetEmailVerified() bool {
	if x != nil {
		return x.EmailVerified
	}
	return false
}

func (x *CreateUserResponse) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *CreateUserResponse) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *CreateUserResponse) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *CreateUserResponse) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *CreateUserResponse) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *CreateUserResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *CreateUserResponse) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`       // User email address
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"` // User password
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_auth_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_auth_messages_proto_rawDescGZIP(), []int{2}
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                   // User ID
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`                                   // JWT access token (expires in 1 hour)
	RefreshToken  string                 `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"` // Refresh token (expires in 30 days)
	ExpiresAt     int64                  `protobuf:"varint,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`         // Unix timestamp when access token expires
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_auth_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_auth_messages_proto_rawDescGZIP(), []int{3}
}

func (x *LoginResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *LoginResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type CreateGuestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IpAddress     string                 `protobuf:"bytes,1,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"` // Guest IP address
	UserAgent     string                 `protobuf:"bytes,2,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"` // Guest user agent
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGuestRequest) Reset() {
	*x = CreateGuestRequest{}
	mi := &file_auth_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGuestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGuestRequest) ProtoMessage() {}

func (x *CreateGuestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGuestRequest.ProtoReflect.Descriptor instead.
func (*CreateGuestRequest) Descriptor() ([]byte, []int) {
	return file_auth_messages_proto_rawDescGZIP(), []int{4}
}

func (x *CreateGuestRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *CreateGuestRequest) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

type CreateGuestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GuestToken    string                 `protobuf:"bytes,1,opt,name=guest_token,json=guestToken,proto3" json:"guest_token,omitempty"` // Guest session token
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGuestResponse) Reset() {
	*x = CreateGuestResponse{}
	mi := &file_auth_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGuestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGuestResponse) ProtoMessage() {}

func (x *CreateGuestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGuestResponse.ProtoReflect.Descriptor instead.
func (*CreateGuestResponse) Descriptor() ([]byte, []int) {
	return file_auth_messages_proto_rawDescGZIP(), []int{5}
}

func (x *CreateGuestResponse) GetGuestToken() string {
	if x != nil {
		return x.GuestToken
	}
	return ""
}

type VerifyGuestTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GuestToken    string                 `protobuf:"bytes,1,opt,name=guest_token,json=guestToken,proto3" json:"guest_token,omitempty"` // Guest token to verify
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyGuestTokenRequest) Reset() {
	*x = VerifyGuestTokenRequest{}
	mi := &file_auth_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyGuestTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyGuestTokenRequest) ProtoMessage() {}

func (x *VerifyGuestTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyGuestTokenRequest.ProtoReflect.Descriptor instead.
func (*VerifyGuestTokenRequest) Descriptor() ([]byte, []int) {
	return file_auth_messages_proto_rawDescGZIP(), []int{6}
}

func (x *VerifyGuestTokenRequest) GetGuestToken() string {
	if x != nil {
		return x.GuestToken
	}
	return ""
}

type VerifyRefreshTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"` // Refresh token to verify
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyRefreshTokenRequest) Reset() {
	*x = VerifyRefreshTokenRequest{}
	mi := &file_auth_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyRefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyRefreshTokenRequest) ProtoMessage() {}

func (x *VerifyRefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyRefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*VerifyRefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_auth_messages_proto_rawDescGZIP(), []int{7}
}

func (x *VerifyRefreshTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type VerifyTokenResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*VerifyTokenResponse_Valid
	//	*VerifyTokenResponse_Error
	Result        isVerifyTokenResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyTokenResponse) Reset() {
	*x = VerifyTokenResponse{}
	mi := &file_auth_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyTokenResponse) ProtoMessage() {}

func (x *VerifyTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyTokenResponse.ProtoReflect.Descriptor instead.
func (*VerifyTokenResponse) Descriptor() ([]byte, []int) {
	return file_auth_messages_proto_rawDescGZIP(), []int{8}
}

func (x *VerifyTokenResponse) GetResult() isVerifyTokenResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *VerifyTokenResponse) GetValid() *TokenValid {
	if x != nil {
		if x, ok := x.Result.(*VerifyTokenResponse_Valid); ok {
			return x.Valid
		}
	}
	return nil
}

func (x *VerifyTokenResponse) GetError() *ErrorResponse {
	if x != nil {
		if x, ok := x.Result.(*VerifyTokenResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isVerifyTokenResponse_Result interface {
	isVerifyTokenResponse_Result()
}

type VerifyTokenResponse_Valid struct {
	Valid *TokenValid `protobuf:"bytes,1,opt,name=valid,proto3,oneof"` // Token is valid
}

type VerifyTokenResponse_Error struct {
	Error *ErrorResponse `protobuf:"bytes,2,opt,name=error,proto3,oneof"` // Token verification failed
}

func (*VerifyTokenResponse_Valid) isVerifyTokenResponse_Result() {}

func (*VerifyTokenResponse_Error) isVerifyTokenResponse_Result() {}

type TokenValid struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`           // User ID from token
	ExpiresAt     int64                  `protobuf:"varint,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"` // Unix timestamp when token expires
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenValid) Reset() {
	*x = TokenValid{}
	mi := &file_auth_messages_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenValid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenValid) ProtoMessage() {}

func (x *TokenValid) ProtoReflect() protoreflect.Message {
	mi := &file_auth_messages_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenValid.ProtoReflect.Descriptor instead.
func (*TokenValid) Descriptor() ([]byte, []int) {
	return file_auth_messages_proto_rawDescGZIP(), []int{9}
}

func (x *TokenValid) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TokenValid) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type RotateRefreshTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"` // Old/current refresh token to rotate
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotateRefreshTokenRequest) Reset() {
	*x = RotateRefreshTokenRequest{}
	mi := &file_auth_messages_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateRefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateRefreshTokenRequest) ProtoMessage() {}

func (x *RotateRefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_messages_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateRefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*RotateRefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_auth_messages_proto_rawDescGZIP(), []int{10}
}

func (x *RotateRefreshTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type RotateRefreshTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                   // User ID
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`                                   // New JWT access token (expires in 1 hour)
	RefreshToken  string                 `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"` // New refresh token (expires in 30 days)
	ExpiresAt     int64                  `protobuf:"varint,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`         // Unix timestamp when access token expires
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotateRefreshTokenResponse) Reset() {
	*x = RotateRefreshTokenResponse{}
	mi := &file_auth_messages_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateRefreshTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateRefreshTokenResponse) ProtoMessage() {}

func (x *RotateRefreshTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_messages_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateRefreshTokenResponse.ProtoReflect.Descriptor instead.
func (*RotateRefreshTokenResponse) Descriptor() ([]byte, []int) {
	return file_auth_messages_proto_rawDescGZIP(), []int{11}
}

func (x *RotateRefreshTokenResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RotateRefreshTokenResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RotateRefreshTokenResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *RotateRefreshTokenResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type ErrorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=auth.ErrorCode" json:"code,omitempty"` // Error code enum
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                // Error message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	mi := &file_auth_messages_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_messages_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_auth_messages_proto_rawDescGZIP(), []int{12}
}

func (x *ErrorResponse) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_ERROR_CODE_UNSPECIFIED
}

func (x *ErrorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_auth_messages_proto protoreflect.FileDescriptor

const file_auth_messages_proto_rawDesc = "" +
	"\n" +
	"\x13auth/messages.proto\x12\x04auth\"\xa4\x01\n" +
	"\x11CreateUserRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12!\n" +
	"\fphone_number\x18\x04 \x01(\tR\vphoneNumber\x12\x1a\n" +
	"\bpassword\x18\x05 \x01(\tR\bpassword\"\xb4\x02\n" +
	"\x12CreateUserResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12%\n" +
	"\x0eemail_verified\x18\x03 \x01(\bR\remailVerified\x12\x1d\n" +
	"\n" +
	"first_name\x18\x04 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x05 \x01(\tR\blastName\x12!\n" +
	"\fphone_number\x18\x06 \x01(\tR\vphoneNumber\x12\x1b\n" +
	"\tis_active\x18\a \x01(\bR\bisActive\x12\x17\n" +
	"\arole_id\x18\b \x01(\tR\x06roleId\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\x03R\tupdatedAt\"@\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\x82\x01\n" +
	"\rLoginResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12#\n" +
	"\rrefresh_token\x18\x03 \x01(\tR\frefreshToken\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\x03R\texpiresAt\"R\n" +
	"\x12CreateGuestRequest\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x01 \x01(\tR\tipAddress\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x02 \x01(\tR\tuserAgent\"6\n" +
	"\x13CreateGuestResponse\x12\x1f\n" +
	"\vguest_token\x18\x01 \x01(\tR\n" +
	"guestToken\":\n" +
	"\x17VerifyGuestTokenRequest\x12\x1f\n" +
	"\vguest_token\x18\x01 \x01(\tR\n" +
	"guestToken\"@\n" +
	"\x19VerifyRefreshTokenRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"v\n" +
	"\x13VerifyTokenResponse\x12(\n" +
	"\x05valid\x18\x01 \x01(\v2\x10.auth.TokenValidH\x00R\x05valid\x12+\n" +
	"\x05error\x18\x02 \x01(\v2\x13.auth.ErrorResponseH\x00R\x05errorB\b\n" +
	"\x06result\"D\n" +
	"\n" +
	"TokenValid\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\x03R\texpiresAt\"@\n" +
	"\x19RotateRefreshTokenRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"\x8f\x01\n" +
	"\x1aRotateRefreshTokenResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12#\n" +
	"\rrefresh_token\x18\x03 \x01(\tR\frefreshToken\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\x03R\texpiresAt\"N\n" +
	"\rErrorResponse\x12#\n" +
	"\x04code\x18\x01 \x01(\x0e2\x0f.auth.ErrorCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*z\n" +
	"\tErrorCode\x12\x1a\n" +
	"\x16ERROR_CODE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13INVALID_CREDENTIALS\x10\x01\x12\x12\n" +
	"\x0eUSER_NOT_FOUND\x10\x02\x12\x11\n" +
	"\rTOKEN_EXPIRED\x10\x03\x12\x11\n" +
	"\rTOKEN_INVALID\x10\x04B\x18Z\x16shared/proto/auth;authb\x06proto3"

var (
	file_auth_messages_proto_rawDescOnce sync.Once
	file_auth_messages_proto_rawDescData []byte
)

func file_auth_messages_proto_rawDescGZIP() []byte {
	file_auth_messages_proto_rawDescOnce.Do(func() {
		file_auth_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_messages_proto_rawDesc), len(file_auth_messages_proto_rawDesc)))
	})
	return file_auth_messages_proto_rawDescData
}

var file_auth_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_auth_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_auth_messages_proto_goTypes = []any{
	(ErrorCode)(0),                     // 0: auth.ErrorCode
	(*CreateUserRequest)(nil),          // 1: auth.CreateUserRequest
	(*CreateUserResponse)(nil),         // 2: auth.CreateUserResponse
	(*LoginRequest)(nil),               // 3: auth.LoginRequest
	(*LoginResponse)(nil),              // 4: auth.LoginResponse
	(*CreateGuestRequest)(nil),         // 5: auth.CreateGuestRequest
	(*CreateGuestResponse)(nil),        // 6: auth.CreateGuestResponse
	(*VerifyGuestTokenRequest)(nil),    // 7: auth.VerifyGuestTokenRequest
	(*VerifyRefreshTokenRequest)(nil),  // 8: auth.VerifyRefreshTokenRequest
	(*VerifyTokenResponse)(nil),        // 9: auth.VerifyTokenResponse
	(*TokenValid)(nil),                 // 10: auth.TokenValid
	(*RotateRefreshTokenRequest)(nil),  // 11: auth.RotateRefreshTokenRequest
	(*RotateRefreshTokenResponse)(nil), // 12: auth.RotateRefreshTokenResponse
	(*ErrorResponse)(nil),              // 13: auth.ErrorResponse
}
var file_auth_messages_proto_depIdxs = []int32{
	10, // 0: auth.VerifyTokenResponse.valid:type_name -> auth.TokenValid
	13, // 1: auth.VerifyTokenResponse.error:type_name -> auth.ErrorResponse
	0,  // 2: auth.ErrorResponse.code:type_name -> auth.ErrorCode
	3,  // [3:3] is the sub-list for method output_type
	3,  // [3:3] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_auth_messages_proto_init() }
func file_auth_messages_proto_init() {
	if File_auth_messages_proto != nil {
		return
	}
	file_auth_messages_proto_msgTypes[8].OneofWrappers = []any{
		(*VerifyTokenResponse_Valid)(nil),
		(*VerifyTokenResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_messages_proto_rawDesc), len(file_auth_messages_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_auth_messages_proto_goTypes,
		DependencyIndexes: file_auth_messages_proto_depIdxs,
		EnumInfos:         file_auth_messages_proto_enumTypes,
		MessageInfos:      file_auth_messages_proto_msgTypes,
	}.Build()
	File_auth_messages_proto = out.File
	file_auth_messages_proto_goTypes = nil
	file_auth_messages_proto_depIdxs = nil
}
