// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: guest.sql

package db

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGuest = `-- name: CreateGuest :one
INSERT INTO
    guests (token_hash, ip_addr, user_agent, expires_at, metadata)
VALUES
    ($1, $2, $3, $4, $5) RETURNING id, token_hash, ip_addr, user_agent, created_at, expires_at, metadata
`

type CreateGuestParams struct {
	TokenHash string             `json:"token_hash"`
	IpAddr    netip.Addr         `json:"ip_addr"`
	UserAgent string             `json:"user_agent"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	Metadata  []byte             `json:"metadata"`
}

func (q *Queries) CreateGuest(ctx context.Context, arg CreateGuestParams) (Guest, error) {
	row := q.db.QueryRow(ctx, createGuest,
		arg.TokenHash,
		arg.IpAddr,
		arg.UserAgent,
		arg.ExpiresAt,
		arg.Metadata,
	)
	var i Guest
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.IpAddr,
		&i.UserAgent,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.Metadata,
	)
	return i, err
}

const getGuestByToken = `-- name: GetGuestByToken :one
SELECT id, token_hash, ip_addr, user_agent, created_at, expires_at, metadata FROM guests g WHERE g.token_hash = $1 limit 1
`

func (q *Queries) GetGuestByToken(ctx context.Context, tokenHash string) (Guest, error) {
	row := q.db.QueryRow(ctx, getGuestByToken, tokenHash)
	var i Guest
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.IpAddr,
		&i.UserAgent,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.Metadata,
	)
	return i, err
}
