// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CreateGuest(ctx context.Context, arg CreateGuestParams) (Guest, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetRoleByName(ctx context.Context, name string) (Role, error)
}

var _ Querier = (*Queries)(nil)
