// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateGuest(ctx context.Context, arg CreateGuestParams) (Guest, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetGuestByToken(ctx context.Context, tokenHash string) (Guest, error)
	GetRefreshTokenByTokenHash(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetRoleByName(ctx context.Context, name string) (Role, error)
	GetUserById(ctx context.Context, id uuid.UUID) (User, error)
}

var _ Querier = (*Queries)(nil)
