// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: refresh_token.sql

package db

import (
	"context"
)

const getRefreshTokenByTokenHash = `-- name: GetRefreshTokenByTokenHash :one
SELECT id, user_id, token_hash, created_at, expires_at, revoked_at FROM refresh_tokens WHERE token_hash = $1 limit 1
`

func (q *Queries) GetRefreshTokenByTokenHash(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByTokenHash, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}
