// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: seller.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createSeller = `-- name: CreateSeller :one
INSERT INTO
    sellers (
     user_id,
     name
    )
VALUES
    ($1, $2) RETURNING id, user_id, name, created_at, updated_at
`

type CreateSellerParams struct {
	UserID uuid.UUID `json:"user_id"`
	Name   string    `json:"name"`
}

func (q *Queries) CreateSeller(ctx context.Context, arg CreateSellerParams) (Seller, error) {
	row := q.db.QueryRow(ctx, createSeller, arg.UserID, arg.Name)
	var i Seller
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
