syntax = "proto3";

package auth;

import "google/protobuf/timestamp.proto";

option go_package = "shared/proto/auth;auth";

// UserService provides user-related RPCs such as creating a new user.
service UserService {
  // CreateUser creates a new user with the provided details.
  rpc CreateUser(CreateUserRequest) returns (CreateUserResponse);

  // CreateGuest creates a new guest with the provided details.
  rpc CreateGuest(CreateGuestRequest) returns (CreateGuestResponse);

  rpc VerifyGuestToken(VerifyGuestTokenRequest) returns (VerifyGuestTokenResponse);

  rpc VerifyRefreshToken(VerifyRefreshTokenRequest) returns (VerifyRefreshTokenResponse);
}

message CreateUserRequest{
  string email        = 1;
  string first_name   = 2;
  string last_name    = 3;
  string phone_number = 4;
  string password     = 5;
}


message CreateUserResponse{
  string                    id             = 1;
  string                    email          = 2;
  bool                      email_verified = 3;
  string                    first_name     = 4;
  string                    last_name      = 5;
  string                    phone_number   = 6;
  bool                      is_active      = 7;
  string                    role_id        = 8;
  google.protobuf.Timestamp created_at     = 9;
  google.protobuf.Timestamp updated_at     = 10;
}

message CreateGuestRequest{
  string ip_address = 1;
  string user_agent = 2;
}

message CreateGuestResponse{
  string guest_token = 1;
}

message VerifyGuestTokenRequest{
  string guest_token = 1;
}

message VerifyGuestTokenResponse{
  oneof result {
    TokenValid valid = 1;
    TokenError error = 2;
  }
}

message VerifyRefreshTokenRequest{
  string refresh_token = 1;
}

message VerifyRefreshTokenResponse {
  oneof result {
    TokenValid valid = 1;
    TokenError error = 2;
  }
}

message TokenValid {
  string user_id    = 1;
  int64  expires_at = 2;
}

message TokenError {
  string code    = 1; // "EXPIRED", "INVALID", "REVOKED"
  string message = 2;
}