syntax = "proto3";

package product;

option go_package = "shared/proto/product;product";

// ===== Product Messages =====
message CreateProductRequest {
  string              user_id     = 1; // ID of the user creating the product
  string              name        = 2; // Product name
  string              description = 3; // Product description
  double              price       = 4; // Product price
  string              category_id = 5; // Product category
  int32               stock       = 6; // Available stock quantity
  map<string, string> attributes  = 7; // Additional product attributes
}

message CreateProductResponse {
  string product_id = 1; // ID of the newly created product
}

message CreateCategoryRequest {
  string                     name        = 1; // Category name
  string                     description = 2; // Category description
  repeated CategoryAttribute attributes  = 3; // List of category attributes
}

message CreateCategoryResponse {
  string category_id = 1; // ID of the newly created category

}

message CategoryAttribute {
  string              key      = 1; // Attribute key
  string              label    = 2; // Attribute label
  string              type     = 3; // Attribute type (e.g., string, number, boolean)
  bool                required = 4; // Whether the attribute is required
  map<string, string> options  = 5; // Options for the attribute (if applicable)
}

enum ProductStatus {
  PRODUCT_STATUS_UNSPECIFIED = 0; // Unspecified status (default)
  ACTIVE                     = 1; // Product is active and available
  INACTIVE                   = 2; // Product is inactive and unavailable
}
