syntax = "proto3";

package product;

import "product/messages.proto";

option go_package = "shared/proto/product;product";

// ProductService provides product-related RPCs such as creating a new product.
service ProductService {
  // CreateProduct creates a new product with the provided details.
  rpc CreateProduct(CreateProductRequest) returns (CreateProductResponse);

  // CreateProductVariant creates a new product variant for an existing product.
  rpc CreateProductVariant(CreateProductVariantRequest) returns (CreateProductVariantResponse);

  // CreateProductVariants creates multiple product variants for an existing product.
  rpc CreateProductVariants(CreateProductVariantsRequest) returns (CreateProductVariantsResponse);

  // CreateCategory creates a new product category with the provided details.
  rpc CreateCategory(CreateCategoryRequest) returns (CreateCategoryResponse);

  // ListProducts retrieves a list of products based on the provided filters.
  rpc ListBuyerProducts(ListBuyerProductsRequest) returns (ListBuyerProductsResponse);

  // ListSellerProducts retrieves a list of products for a specific seller.
  rpc ListSellerProducts(ListSellerProductsRequest) returns (ListSellerProductsResponse);

  // GetProduct retrieves detailed information about a specific product by its ID.
  rpc GetProductByID(GetProductByIDRequest) returns (GetProductByIDResponse);

  // GetProductBySlug retrieves detailed information about a specific product by its slug.
  rpc GetProductBySlug(GetProductBySlugRequest) returns (GetProductBySlugResponse);

  // UploadProductImages uploads images for a specific product.
  rpc UploadProductImages(UploadProductImagesRequest) returns (UploadProductImagesResponse);
}
