// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/domain.go
//
// Generated by this command:
//
//	mockgen -source=./internal/domain/domain.go -destination=mocks/mock_repository.go -package=mocks -mock_names UserRepository=MockUserRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	domain "yaak-kaii/services/auth-service/internal/domain"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
	isgomock struct{}
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// CreateUser mocks base method.
func (m *MockUserRepository) CreateUser(ctx context.Context, user *domain.UserModel) (*domain.UserModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, user)
	ret0, _ := ret[0].(*domain.UserModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockUserRepositoryMockRecorder) CreateUser(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockUserRepository)(nil).CreateUser), ctx, user)
}

// GetUserByEmail mocks base method.
func (m *MockUserRepository) GetUserByEmail(ctx context.Context, email string) (*domain.UserModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmail", ctx, email)
	ret0, _ := ret[0].(*domain.UserModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockUserRepositoryMockRecorder) GetUserByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*MockUserRepository)(nil).GetUserByEmail), ctx, email)
}

// GetUserByID mocks base method.
func (m *MockUserRepository) GetUserByID(ctx context.Context, id uuid.UUID) (*domain.UserModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, id)
	ret0, _ := ret[0].(*domain.UserModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockUserRepositoryMockRecorder) GetUserByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockUserRepository)(nil).GetUserByID), ctx, id)
}

// MockGuestRepository is a mock of GuestRepository interface.
type MockGuestRepository struct {
	ctrl     *gomock.Controller
	recorder *MockGuestRepositoryMockRecorder
	isgomock struct{}
}

// MockGuestRepositoryMockRecorder is the mock recorder for MockGuestRepository.
type MockGuestRepositoryMockRecorder struct {
	mock *MockGuestRepository
}

// NewMockGuestRepository creates a new mock instance.
func NewMockGuestRepository(ctrl *gomock.Controller) *MockGuestRepository {
	mock := &MockGuestRepository{ctrl: ctrl}
	mock.recorder = &MockGuestRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGuestRepository) EXPECT() *MockGuestRepositoryMockRecorder {
	return m.recorder
}

// CreateGuest mocks base method.
func (m *MockGuestRepository) CreateGuest(ctx context.Context, guest *domain.GuestModel) (*domain.GuestModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateGuest", ctx, guest)
	ret0, _ := ret[0].(*domain.GuestModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateGuest indicates an expected call of CreateGuest.
func (mr *MockGuestRepositoryMockRecorder) CreateGuest(ctx, guest any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateGuest", reflect.TypeOf((*MockGuestRepository)(nil).CreateGuest), ctx, guest)
}

// GetGuestByToken mocks base method.
func (m *MockGuestRepository) GetGuestByToken(ctx context.Context, token string) (*domain.GuestModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGuestByToken", ctx, token)
	ret0, _ := ret[0].(*domain.GuestModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGuestByToken indicates an expected call of GetGuestByToken.
func (mr *MockGuestRepositoryMockRecorder) GetGuestByToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGuestByToken", reflect.TypeOf((*MockGuestRepository)(nil).GetGuestByToken), ctx, token)
}

// MockRefreshTokenRepository is a mock of RefreshTokenRepository interface.
type MockRefreshTokenRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRefreshTokenRepositoryMockRecorder
	isgomock struct{}
}

// MockRefreshTokenRepositoryMockRecorder is the mock recorder for MockRefreshTokenRepository.
type MockRefreshTokenRepositoryMockRecorder struct {
	mock *MockRefreshTokenRepository
}

// NewMockRefreshTokenRepository creates a new mock instance.
func NewMockRefreshTokenRepository(ctrl *gomock.Controller) *MockRefreshTokenRepository {
	mock := &MockRefreshTokenRepository{ctrl: ctrl}
	mock.recorder = &MockRefreshTokenRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRefreshTokenRepository) EXPECT() *MockRefreshTokenRepositoryMockRecorder {
	return m.recorder
}

// CreateRefreshToken mocks base method.
func (m *MockRefreshTokenRepository) CreateRefreshToken(ctx context.Context, token *domain.RefreshTokenModel) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRefreshToken", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateRefreshToken indicates an expected call of CreateRefreshToken.
func (mr *MockRefreshTokenRepositoryMockRecorder) CreateRefreshToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRefreshToken", reflect.TypeOf((*MockRefreshTokenRepository)(nil).CreateRefreshToken), ctx, token)
}

// GetRefreshTokenByHash mocks base method.
func (m *MockRefreshTokenRepository) GetRefreshTokenByHash(ctx context.Context, hash string) (*domain.RefreshTokenModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRefreshTokenByHash", ctx, hash)
	ret0, _ := ret[0].(*domain.RefreshTokenModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRefreshTokenByHash indicates an expected call of GetRefreshTokenByHash.
func (mr *MockRefreshTokenRepositoryMockRecorder) GetRefreshTokenByHash(ctx, hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRefreshTokenByHash", reflect.TypeOf((*MockRefreshTokenRepository)(nil).GetRefreshTokenByHash), ctx, hash)
}

// MockRoleRepository is a mock of RoleRepository interface.
type MockRoleRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRoleRepositoryMockRecorder
	isgomock struct{}
}

// MockRoleRepositoryMockRecorder is the mock recorder for MockRoleRepository.
type MockRoleRepositoryMockRecorder struct {
	mock *MockRoleRepository
}

// NewMockRoleRepository creates a new mock instance.
func NewMockRoleRepository(ctrl *gomock.Controller) *MockRoleRepository {
	mock := &MockRoleRepository{ctrl: ctrl}
	mock.recorder = &MockRoleRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoleRepository) EXPECT() *MockRoleRepositoryMockRecorder {
	return m.recorder
}

// GetRoleByName mocks base method.
func (m *MockRoleRepository) GetRoleByName(ctx context.Context, name string) (*domain.RoleModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoleByName", ctx, name)
	ret0, _ := ret[0].(*domain.RoleModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoleByName indicates an expected call of GetRoleByName.
func (mr *MockRoleRepositoryMockRecorder) GetRoleByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoleByName", reflect.TypeOf((*MockRoleRepository)(nil).GetRoleByName), ctx, name)
}
