apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: yaak-kaii/auth-service
          ports:
            - containerPort: 9090
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          env:
            - name: PG_URI
              valueFrom:
                secretKeyRef:
                  name: pg
                  key: uri
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt
                  key: jwt-secret
            - name: JWT_ISSUER
              valueFrom:
                secretKeyRef:
                  name: jwt
                  key: jwt-issuer
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth-service
  ports:
    - port: 9090
      name: grpc
      targetPort: 9090
  type: ClusterIP
