apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: yaak-kaii/product-service
          ports:
            - containerPort: 9091
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          env:
            - name: PG_URI
              valueFrom:
                secretKeyRef:
                  name: pg
                  key: PG_URI
            - name: PG_USERNAME
              valueFrom:
                secretKeyRef:
                  name: pg
                  key: PG_USERNAME
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg
                  key: PG_PASSWORD
            - name: PG_DATABASE
              valueFrom:
                secretKeyRef:
                  name: pg
                  key: PG_DATABASE
            - name: PG_PORT
              valueFrom:
                secretKeyRef:
                  name: pg
                  key: PG_PORT
            - name: PG_HOST
              valueFrom:
                secretKeyRef:
                  name: pg
                  key: PG_HOST
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  selector:
    app: product-service
  ports:
    - port: 9091
      name: grpc
      targetPort: 9091
  type: ClusterIP
