// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: order/messages.proto

package order

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ===== Order Messages =====
type CreateOrderRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                            // User ID
	GuestId         string                 `protobuf:"bytes,2,opt,name=guest_id,json=guestId,proto3" json:"guest_id,omitempty"`                         // Guest ID, optional
	TotalAmount     string                 `protobuf:"bytes,3,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`             // Total amount
	Currency        string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`                                      // Currency
	Status          string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`                                          // Order status
	ShippingAddress *ShippingAddress       `protobuf:"bytes,6,opt,name=shipping_address,json=shippingAddress,proto3" json:"shipping_address,omitempty"` // Shipping address
	CreatedAt       int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`                  // Order creation timestamp
	UpdatedAt       int64                  `protobuf:"varint,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`                  // Last update timestamp
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_order_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_messages_proto_rawDescGZIP(), []int{0}
}

func (x *CreateOrderRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateOrderRequest) GetGuestId() string {
	if x != nil {
		return x.GuestId
	}
	return ""
}

func (x *CreateOrderRequest) GetTotalAmount() string {
	if x != nil {
		return x.TotalAmount
	}
	return ""
}

func (x *CreateOrderRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreateOrderRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateOrderRequest) GetShippingAddress() *ShippingAddress {
	if x != nil {
		return x.ShippingAddress
	}
	return nil
}

func (x *CreateOrderRequest) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *CreateOrderRequest) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type CreateOrderResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	OrderId         string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`                         // Order ID
	UserId          string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                            // User ID
	GuestId         string                 `protobuf:"bytes,3,opt,name=guest_id,json=guestId,proto3" json:"guest_id,omitempty"`                         // Guest ID, optional
	TotalAmount     string                 `protobuf:"bytes,4,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`             // Total amount
	Currency        string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`                                      // Currency
	Status          string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`                                          // Order status
	ShippingAddress *ShippingAddress       `protobuf:"bytes,7,opt,name=shipping_address,json=shippingAddress,proto3" json:"shipping_address,omitempty"` // Shipping address
	CreatedAt       int64                  `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`                  // Order creation timestamp
	UpdatedAt       int64                  `protobuf:"varint,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`                  // Last update timestamp
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateOrderResponse) Reset() {
	*x = CreateOrderResponse{}
	mi := &file_order_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderResponse) ProtoMessage() {}

func (x *CreateOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderResponse.ProtoReflect.Descriptor instead.
func (*CreateOrderResponse) Descriptor() ([]byte, []int) {
	return file_order_messages_proto_rawDescGZIP(), []int{1}
}

func (x *CreateOrderResponse) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CreateOrderResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateOrderResponse) GetGuestId() string {
	if x != nil {
		return x.GuestId
	}
	return ""
}

func (x *CreateOrderResponse) GetTotalAmount() string {
	if x != nil {
		return x.TotalAmount
	}
	return ""
}

func (x *CreateOrderResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreateOrderResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateOrderResponse) GetShippingAddress() *ShippingAddress {
	if x != nil {
		return x.ShippingAddress
	}
	return nil
}

func (x *CreateOrderResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *CreateOrderResponse) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type ShippingAddress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Street        string                 `protobuf:"bytes,1,opt,name=street,proto3" json:"street,omitempty"`                           // Street address
	City          string                 `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`                               // City
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`                             // State or province
	PostalCode    string                 `protobuf:"bytes,4,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"` // Postal or ZIP code
	Country       string                 `protobuf:"bytes,5,opt,name=country,proto3" json:"country,omitempty"`                         // Country
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShippingAddress) Reset() {
	*x = ShippingAddress{}
	mi := &file_order_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShippingAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShippingAddress) ProtoMessage() {}

func (x *ShippingAddress) ProtoReflect() protoreflect.Message {
	mi := &file_order_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShippingAddress.ProtoReflect.Descriptor instead.
func (*ShippingAddress) Descriptor() ([]byte, []int) {
	return file_order_messages_proto_rawDescGZIP(), []int{2}
}

func (x *ShippingAddress) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *ShippingAddress) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *ShippingAddress) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ShippingAddress) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

func (x *ShippingAddress) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

// ===== Order Items Messages =====
type CreateOrderItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"` // Order ID
	Items         []*OrderItem           `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`                    // List of order items
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderItemsRequest) Reset() {
	*x = CreateOrderItemsRequest{}
	mi := &file_order_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderItemsRequest) ProtoMessage() {}

func (x *CreateOrderItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderItemsRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderItemsRequest) Descriptor() ([]byte, []int) {
	return file_order_messages_proto_rawDescGZIP(), []int{3}
}

func (x *CreateOrderItemsRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CreateOrderItemsRequest) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

// OrderItem represents a single item in an order.
type CreateOrderItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"` // Order ID
	Items         []*OrderItem           `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`                    // List of order items
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderItemsResponse) Reset() {
	*x = CreateOrderItemsResponse{}
	mi := &file_order_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderItemsResponse) ProtoMessage() {}

func (x *CreateOrderItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderItemsResponse.ProtoReflect.Descriptor instead.
func (*CreateOrderItemsResponse) Descriptor() ([]byte, []int) {
	return file_order_messages_proto_rawDescGZIP(), []int{4}
}

func (x *CreateOrderItemsResponse) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CreateOrderItemsResponse) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

// OrderItem represents a single item in an order.
type OrderItem struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProductId       string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`                     // Product ID
	Quantity        int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`                                       // Quantity of the product
	Sku             string                 `protobuf:"bytes,3,opt,name=sku,proto3" json:"sku,omitempty"`                                                  // SKU of the product
	NameAtPurchase  string                 `protobuf:"bytes,4,opt,name=name_at_purchase,json=nameAtPurchase,proto3" json:"name_at_purchase,omitempty"`    // Name at the time of purchase
	PriceAtPurchase string                 `protobuf:"bytes,5,opt,name=price_at_purchase,json=priceAtPurchase,proto3" json:"price_at_purchase,omitempty"` // Price at the time of purchase
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OrderItem) Reset() {
	*x = OrderItem{}
	mi := &file_order_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItem) ProtoMessage() {}

func (x *OrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_order_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItem.ProtoReflect.Descriptor instead.
func (*OrderItem) Descriptor() ([]byte, []int) {
	return file_order_messages_proto_rawDescGZIP(), []int{5}
}

func (x *OrderItem) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *OrderItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *OrderItem) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *OrderItem) GetNameAtPurchase() string {
	if x != nil {
		return x.NameAtPurchase
	}
	return ""
}

func (x *OrderItem) GetPriceAtPurchase() string {
	if x != nil {
		return x.PriceAtPurchase
	}
	return ""
}

var File_order_messages_proto protoreflect.FileDescriptor

const file_order_messages_proto_rawDesc = "" +
	"\n" +
	"\x14order/messages.proto\x12\x05order\"\xa0\x02\n" +
	"\x12CreateOrderRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bguest_id\x18\x02 \x01(\tR\aguestId\x12!\n" +
	"\ftotal_amount\x18\x03 \x01(\tR\vtotalAmount\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12A\n" +
	"\x10shipping_address\x18\x06 \x01(\v2\x16.order.ShippingAddressR\x0fshippingAddress\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\x03R\tupdatedAt\"\xbc\x02\n" +
	"\x13CreateOrderResponse\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x19\n" +
	"\bguest_id\x18\x03 \x01(\tR\aguestId\x12!\n" +
	"\ftotal_amount\x18\x04 \x01(\tR\vtotalAmount\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12A\n" +
	"\x10shipping_address\x18\a \x01(\v2\x16.order.ShippingAddressR\x0fshippingAddress\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\x03R\tupdatedAt\"\x8e\x01\n" +
	"\x0fShippingAddress\x12\x16\n" +
	"\x06street\x18\x01 \x01(\tR\x06street\x12\x12\n" +
	"\x04city\x18\x02 \x01(\tR\x04city\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12\x1f\n" +
	"\vpostal_code\x18\x04 \x01(\tR\n" +
	"postalCode\x12\x18\n" +
	"\acountry\x18\x05 \x01(\tR\acountry\"\\\n" +
	"\x17CreateOrderItemsRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12&\n" +
	"\x05items\x18\x02 \x03(\v2\x10.order.OrderItemR\x05items\"]\n" +
	"\x18CreateOrderItemsResponse\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12&\n" +
	"\x05items\x18\x02 \x03(\v2\x10.order.OrderItemR\x05items\"\xae\x01\n" +
	"\tOrderItem\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\x12\x10\n" +
	"\x03sku\x18\x03 \x01(\tR\x03sku\x12(\n" +
	"\x10name_at_purchase\x18\x04 \x01(\tR\x0enameAtPurchase\x12*\n" +
	"\x11price_at_purchase\x18\x05 \x01(\tR\x0fpriceAtPurchaseB\x1aZ\x18shared/proto/order;orderb\x06proto3"

var (
	file_order_messages_proto_rawDescOnce sync.Once
	file_order_messages_proto_rawDescData []byte
)

func file_order_messages_proto_rawDescGZIP() []byte {
	file_order_messages_proto_rawDescOnce.Do(func() {
		file_order_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_messages_proto_rawDesc), len(file_order_messages_proto_rawDesc)))
	})
	return file_order_messages_proto_rawDescData
}

var file_order_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_order_messages_proto_goTypes = []any{
	(*CreateOrderRequest)(nil),       // 0: order.CreateOrderRequest
	(*CreateOrderResponse)(nil),      // 1: order.CreateOrderResponse
	(*ShippingAddress)(nil),          // 2: order.ShippingAddress
	(*CreateOrderItemsRequest)(nil),  // 3: order.CreateOrderItemsRequest
	(*CreateOrderItemsResponse)(nil), // 4: order.CreateOrderItemsResponse
	(*OrderItem)(nil),                // 5: order.OrderItem
}
var file_order_messages_proto_depIdxs = []int32{
	2, // 0: order.CreateOrderRequest.shipping_address:type_name -> order.ShippingAddress
	2, // 1: order.CreateOrderResponse.shipping_address:type_name -> order.ShippingAddress
	5, // 2: order.CreateOrderItemsRequest.items:type_name -> order.OrderItem
	5, // 3: order.CreateOrderItemsResponse.items:type_name -> order.OrderItem
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_order_messages_proto_init() }
func file_order_messages_proto_init() {
	if File_order_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_messages_proto_rawDesc), len(file_order_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_order_messages_proto_goTypes,
		DependencyIndexes: file_order_messages_proto_depIdxs,
		MessageInfos:      file_order_messages_proto_msgTypes,
	}.Build()
	File_order_messages_proto = out.File
	file_order_messages_proto_goTypes = nil
	file_order_messages_proto_depIdxs = nil
}
