// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: order/service.proto

package order

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_order_service_proto protoreflect.FileDescriptor

const file_order_service_proto_rawDesc = "" +
	"\n" +
	"\x13order/service.proto\x12\x05order\x1a\x14order/messages.proto2\xa9\x01\n" +
	"\fOrderService\x12D\n" +
	"\vCreateOrder\x12\x19.order.CreateOrderRequest\x1a\x1a.order.CreateOrderResponse\x12S\n" +
	"\x10CreateOrderItems\x12\x1e.order.CreateOrderItemsRequest\x1a\x1f.order.CreateOrderItemsResponseB\x1aZ\x18shared/proto/order;orderb\x06proto3"

var file_order_service_proto_goTypes = []any{
	(*CreateOrderRequest)(nil),       // 0: order.CreateOrderRequest
	(*CreateOrderItemsRequest)(nil),  // 1: order.CreateOrderItemsRequest
	(*CreateOrderResponse)(nil),      // 2: order.CreateOrderResponse
	(*CreateOrderItemsResponse)(nil), // 3: order.CreateOrderItemsResponse
}
var file_order_service_proto_depIdxs = []int32{
	0, // 0: order.OrderService.CreateOrder:input_type -> order.CreateOrderRequest
	1, // 1: order.OrderService.CreateOrderItems:input_type -> order.CreateOrderItemsRequest
	2, // 2: order.OrderService.CreateOrder:output_type -> order.CreateOrderResponse
	3, // 3: order.OrderService.CreateOrderItems:output_type -> order.CreateOrderItemsResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_order_service_proto_init() }
func file_order_service_proto_init() {
	if File_order_service_proto != nil {
		return
	}
	file_order_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_service_proto_rawDesc), len(file_order_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_service_proto_goTypes,
		DependencyIndexes: file_order_service_proto_depIdxs,
	}.Build()
	File_order_service_proto = out.File
	file_order_service_proto_goTypes = nil
	file_order_service_proto_depIdxs = nil
}
